import type { Run, RunEvent } from "@aegis/contracts";
import { eventId, runId, taskId, workerId, workflowId } from "@aegis/types";

export function getInitialSeedRuns(): Run[] {
  const baseTime = Date.now();

  return [
    {
      id: runId("run-001"),
      goal: "Analyze repository performance bottlenecks and optimize database queries",
      status: "running",
      progress: 60,
      createdAt: new Date(baseTime - 1000 * 60 * 15).toISOString(),
      updatedAt: new Date(baseTime - 1000 * 60 * 2).toISOString(),
      workflow: {
        id: workflowId("wf-001"),
        name: "Repository Performance Analysis Pipeline",
        tasks: [
          {
            id: taskId("task-101"),
            name: "Planning & Workspace Scope",
            status: "completed",
            description: "Scan directory structure, locate configuration files, and establish task execution graph.",
            worker: workerId("worker-node-alpha"),
            startedAt: new Date(baseTime - 1000 * 60 * 15).toISOString(),
            completedAt: new Date(baseTime - 1000 * 60 * 13).toISOString(),
            attemptCount: 1,
            output: "Successfully mapped workspace. Discovered 3 apps and 5 core packages.",
          },
          {
            id: taskId("task-102"),
            name: "Repository Code Inspection",
            status: "completed",
            description: "Analyze AST patterns, query call sites, and identify unindexed query filters.",
            worker: workerId("worker-node-beta"),
            startedAt: new Date(baseTime - 1000 * 60 * 13).toISOString(),
            completedAt: new Date(baseTime - 1000 * 60 * 9).toISOString(),
            attemptCount: 1,
            output: "Identified 4 database access call-sites in api package. 2 missing composite index candidates.",
          },
          {
            id: taskId("task-103"),
            name: "Query Execution Profiling",
            status: "running",
            description: "Simulate concurrent query execution and measure latency under simulated connection pool pressure.",
            worker: workerId("worker-node-gamma"),
            startedAt: new Date(baseTime - 1000 * 60 * 9).toISOString(),
            attemptCount: 1,
            output: "Profiling active: 80% through benchmark matrix.",
          },
          {
            id: taskId("task-104"),
            name: "Bottleneck Evaluation & Ranking",
            status: "queued",
            description: "Aggregate latency profiles, evaluate p95/p99 spikes, and rank critical hotspots.",
            attemptCount: 0,
          },
          {
            id: taskId("task-105"),
            name: "Final Performance Report",
            status: "pending",
            description: "Compile structured findings, mitigation diff suggestions, and summary report.",
            attemptCount: 0,
          },
        ],
      },
      tasks: [
        {
          id: taskId("task-101"),
          name: "Planning & Workspace Scope",
          status: "completed",
          description: "Scan directory structure, locate configuration files, and establish task execution graph.",
          worker: workerId("worker-node-alpha"),
          startedAt: new Date(baseTime - 1000 * 60 * 15).toISOString(),
          completedAt: new Date(baseTime - 1000 * 60 * 13).toISOString(),
          attemptCount: 1,
          output: "Successfully mapped workspace. Discovered 3 apps and 5 core packages.",
        },
        {
          id: taskId("task-102"),
          name: "Repository Code Inspection",
          status: "completed",
          description: "Analyze AST patterns, query call sites, and identify unindexed query filters.",
          worker: workerId("worker-node-beta"),
          startedAt: new Date(baseTime - 1000 * 60 * 13).toISOString(),
          completedAt: new Date(baseTime - 1000 * 60 * 9).toISOString(),
          attemptCount: 1,
          output: "Identified 4 database access call-sites in api package. 2 missing composite index candidates.",
        },
        {
          id: taskId("task-103"),
          name: "Query Execution Profiling",
          status: "running",
          description: "Simulate concurrent query execution and measure latency under simulated connection pool pressure.",
          worker: workerId("worker-node-gamma"),
          startedAt: new Date(baseTime - 1000 * 60 * 9).toISOString(),
          attemptCount: 1,
          output: "Profiling active: 80% through benchmark matrix.",
        },
        {
          id: taskId("task-104"),
          name: "Bottleneck Evaluation & Ranking",
          status: "queued",
          description: "Aggregate latency profiles, evaluate p95/p99 spikes, and rank critical hotspots.",
          attemptCount: 0,
        },
        {
          id: taskId("task-105"),
          name: "Final Performance Report",
          status: "pending",
          description: "Compile structured findings, mitigation diff suggestions, and summary report.",
          attemptCount: 0,
        },
      ],
    },
    {
      id: runId("run-002"),
      goal: "Implement comprehensive zero-trust authentication protocol for edge workers",
      status: "completed",
      progress: 100,
      createdAt: new Date(baseTime - 1000 * 60 * 120).toISOString(),
      updatedAt: new Date(baseTime - 1000 * 60 * 95).toISOString(),
      workflow: {
        id: workflowId("wf-002"),
        name: "Zero-Trust Worker Authentication Pipeline",
        tasks: [
          {
            id: taskId("task-201"),
            name: "Threat Model & Architecture Spec",
            status: "completed",
            description: "Review mutual TLS token rotation and key exchange attack vectors.",
            worker: workerId("worker-node-alpha"),
            startedAt: new Date(baseTime - 1000 * 60 * 120).toISOString(),
            completedAt: new Date(baseTime - 1000 * 60 * 110).toISOString(),
            attemptCount: 1,
            output: "Identified need for ephemeral JWT signing with 15-minute lease cycles.",
          },
          {
            id: taskId("task-202"),
            name: "Cryptographic Key Rotation Logic",
            status: "completed",
            description: "Develop automated ECDSA P-256 keypair generator and distribution protocol.",
            worker: workerId("worker-node-beta"),
            startedAt: new Date(baseTime - 1000 * 60 * 110).toISOString(),
            completedAt: new Date(baseTime - 1000 * 60 * 100).toISOString(),
            attemptCount: 1,
            output: "Implemented key generator with zero-dependency crypto module.",
          },
          {
            id: taskId("task-203"),
            name: "Integration Test Verification",
            status: "completed",
            description: "Run 250 simulated worker connection attempts across latency thresholds.",
            worker: workerId("worker-node-gamma"),
            startedAt: new Date(baseTime - 1000 * 60 * 100).toISOString(),
            completedAt: new Date(baseTime - 1000 * 60 * 95).toISOString(),
            attemptCount: 1,
            output: "All 250 worker authentications passed with 0 token leakage.",
          },
        ],
      },
      tasks: [
        {
          id: taskId("task-201"),
          name: "Threat Model & Architecture Spec",
          status: "completed",
          description: "Review mutual TLS token rotation and key exchange attack vectors.",
          worker: workerId("worker-node-alpha"),
          startedAt: new Date(baseTime - 1000 * 60 * 120).toISOString(),
          completedAt: new Date(baseTime - 1000 * 60 * 110).toISOString(),
          attemptCount: 1,
          output: "Identified need for ephemeral JWT signing with 15-minute lease cycles.",
        },
        {
          id: taskId("task-202"),
          name: "Cryptographic Key Rotation Logic",
          status: "completed",
          description: "Develop automated ECDSA P-256 keypair generator and distribution protocol.",
          worker: workerId("worker-node-beta"),
          startedAt: new Date(baseTime - 1000 * 60 * 110).toISOString(),
          completedAt: new Date(baseTime - 1000 * 60 * 100).toISOString(),
          attemptCount: 1,
          output: "Implemented key generator with zero-dependency crypto module.",
        },
        {
          id: taskId("task-203"),
          name: "Integration Test Verification",
          status: "completed",
          description: "Run 250 simulated worker connection attempts across latency thresholds.",
          worker: workerId("worker-node-gamma"),
          startedAt: new Date(baseTime - 1000 * 60 * 100).toISOString(),
          completedAt: new Date(baseTime - 1000 * 60 * 95).toISOString(),
          attemptCount: 1,
          output: "All 250 worker authentications passed with 0 token leakage.",
        },
      ],
      result: {
        summary: "Zero-trust edge worker authentication protocol successfully verified and certified.",
        reportMarkdown: "# Zero-Trust Worker Authentication Report\n\nAll mutual TLS handshake verifications completed successfully.",
        metrics: {
          durationMs: 1500000,
          tasksTotal: 3,
          tasksCompleted: 3,
          toolInvocations: 14,
        },
        artifacts: [
          {
            name: "auth-policy.json",
            type: "application/json",
            path: "/artifacts/run-002/auth-policy.json",
            sizeBytes: 4096,
          },
        ],
      },
    },
    {
      id: runId("run-003"),
      goal: "Automate cross-region PostgreSQL replica failover under sustained traffic burst",
      status: "failed",
      progress: 45,
      createdAt: new Date(baseTime - 1000 * 60 * 240).toISOString(),
      updatedAt: new Date(baseTime - 1000 * 60 * 210).toISOString(),
      workflow: {
        id: workflowId("wf-003"),
        name: "Disaster Recovery Failover Simulation",
        tasks: [
          {
            id: taskId("task-301"),
            name: "Primary Instance Termination Simulation",
            status: "completed",
            description: "Sever network connectivity to simulated primary node.",
            worker: workerId("worker-node-alpha"),
            startedAt: new Date(baseTime - 1000 * 60 * 240).toISOString(),
            completedAt: new Date(baseTime - 1000 * 60 * 235).toISOString(),
            attemptCount: 1,
            output: "Simulated partition active. Heartbeat missed 3 times.",
          },
          {
            id: taskId("task-302"),
            name: "Consensus Leader Election",
            status: "failed",
            description: "Trigger Raft consensus election across surviving read replicas.",
            worker: workerId("worker-node-beta"),
            startedAt: new Date(baseTime - 1000 * 60 * 235).toISOString(),
            completedAt: new Date(baseTime - 1000 * 60 * 210).toISOString(),
            attemptCount: 3,
            error: "Split-brain threshold reached: quorum could not be established within 25000ms timeout.",
          },
        ],
      },
      tasks: [
        {
          id: taskId("task-301"),
          name: "Primary Instance Termination Simulation",
          status: "completed",
          description: "Sever network connectivity to simulated primary node.",
          worker: workerId("worker-node-alpha"),
          startedAt: new Date(baseTime - 1000 * 60 * 240).toISOString(),
          completedAt: new Date(baseTime - 1000 * 60 * 235).toISOString(),
          attemptCount: 1,
          output: "Simulated partition active. Heartbeat missed 3 times.",
        },
        {
          id: taskId("task-302"),
          name: "Consensus Leader Election",
          status: "failed",
          description: "Trigger Raft consensus election across surviving read replicas.",
          worker: workerId("worker-node-beta"),
          startedAt: new Date(baseTime - 1000 * 60 * 235).toISOString(),
          completedAt: new Date(baseTime - 1000 * 60 * 210).toISOString(),
          attemptCount: 3,
          error: "Split-brain threshold reached: quorum could not be established within 25000ms timeout.",
        },
      ],
      result: {
        summary: "Failover simulation failed due to quorum partition timeout.",
        reportMarkdown: "# Failover Failure Postmortem\n\nQuorum consensus failed during simulated network partition.",
        metrics: {
          durationMs: 1800000,
          tasksTotal: 2,
          tasksCompleted: 1,
          toolInvocations: 8,
        },
      },
    },
    {
      id: runId("run-004"),
      goal: "Generate Diataxis-compliant architectural documentation from distributed worker codebase",
      status: "pending",
      progress: 0,
      createdAt: new Date(baseTime - 1000 * 60 * 5).toISOString(),
      updatedAt: new Date(baseTime - 1000 * 60 * 5).toISOString(),
      workflow: {
        id: workflowId("wf-004"),
        name: "Diataxis Documentation Synthesis",
        tasks: [
          {
            id: taskId("task-401"),
            name: "Codebase Symbol Indexing",
            status: "pending",
            description: "Extract public interfaces, docstrings, and exported types across all packages.",
            attemptCount: 0,
          },
          {
            id: taskId("task-402"),
            name: "Tutorial & Guide Draft Synthesis",
            status: "pending",
            description: "Formulate step-by-step onboarding walkthroughs.",
            attemptCount: 0,
          },
        ],
      },
      tasks: [
        {
          id: taskId("task-401"),
          name: "Codebase Symbol Indexing",
          status: "pending",
          description: "Extract public interfaces, docstrings, and exported types across all packages.",
          attemptCount: 0,
        },
        {
          id: taskId("task-402"),
          name: "Tutorial & Guide Draft Synthesis",
          status: "pending",
          description: "Formulate step-by-step onboarding walkthroughs.",
          attemptCount: 0,
        },
      ],
    },
  ];
}

export function getInitialSeedEvents(): Record<string, RunEvent[]> {
  const baseTime = Date.now();

  return {
    "run-001": [
      {
        id: eventId("ev-001"),
        runId: runId("run-001"),
        type: "run_created",
        severity: "info",
        timestamp: new Date(baseTime - 1000 * 60 * 15).toISOString(),
        message: "Run created with goal: 'Analyze repository performance bottlenecks and optimize database queries'",
      },
      {
        id: eventId("ev-002"),
        runId: runId("run-001"),
        type: "workflow_started",
        severity: "info",
        timestamp: new Date(baseTime - 1000 * 60 * 15 + 1500).toISOString(),
        message: "Workflow 'Repository Performance Analysis Pipeline' initialized with 5 tasks",
      },
      {
        id: eventId("ev-003"),
        runId: runId("run-001"),
        type: "task_scheduled",
        severity: "info",
        timestamp: new Date(baseTime - 1000 * 60 * 15 + 3000).toISOString(),
        taskId: taskId("task-101"),
        taskName: "Planning & Workspace Scope",
        worker: workerId("worker-node-alpha"),
        message: "Task 'Planning & Workspace Scope' scheduled to worker-node-alpha",
      },
      {
        id: eventId("ev-004"),
        runId: runId("run-001"),
        type: "task_started",
        severity: "info",
        timestamp: new Date(baseTime - 1000 * 60 * 15 + 4000).toISOString(),
        taskId: taskId("task-101"),
        taskName: "Planning & Workspace Scope",
        worker: workerId("worker-node-alpha"),
        message: "Worker node alpha began task execution",
      },
      {
        id: eventId("ev-005"),
        runId: runId("run-001"),
        type: "tool_invoked",
        severity: "info",
        timestamp: new Date(baseTime - 1000 * 60 * 14).toISOString(),
        taskId: taskId("task-101"),
        message: "Tool invoked: repository_ast_scanner (duration: 412ms)",
      },
      {
        id: eventId("ev-006"),
        runId: runId("run-001"),
        type: "task_completed",
        severity: "success",
        timestamp: new Date(baseTime - 1000 * 60 * 13).toISOString(),
        taskId: taskId("task-101"),
        taskName: "Planning & Workspace Scope",
        worker: workerId("worker-node-alpha"),
        message: "Task 'Planning & Workspace Scope' completed successfully",
      },
      {
        id: eventId("ev-007"),
        runId: runId("run-001"),
        type: "task_scheduled",
        severity: "info",
        timestamp: new Date(baseTime - 1000 * 60 * 13 + 500).toISOString(),
        taskId: taskId("task-102"),
        taskName: "Repository Code Inspection",
        worker: workerId("worker-node-beta"),
        message: "Task 'Repository Code Inspection' scheduled to worker-node-beta",
      },
      {
        id: eventId("ev-008"),
        runId: runId("run-001"),
        type: "task_started",
        severity: "info",
        timestamp: new Date(baseTime - 1000 * 60 * 13 + 1000).toISOString(),
        taskId: taskId("task-102"),
        taskName: "Repository Code Inspection",
        worker: workerId("worker-node-beta"),
        message: "Worker node beta began task execution",
      },
      {
        id: eventId("ev-009"),
        runId: runId("run-001"),
        type: "task_completed",
        severity: "success",
        timestamp: new Date(baseTime - 1000 * 60 * 9).toISOString(),
        taskId: taskId("task-102"),
        taskName: "Repository Code Inspection",
        worker: workerId("worker-node-beta"),
        message: "Task 'Repository Code Inspection' completed successfully. Found 2 indexing hotspots.",
      },
      {
        id: eventId("ev-010"),
        runId: runId("run-001"),
        type: "task_started",
        severity: "info",
        timestamp: new Date(baseTime - 1000 * 60 * 9 + 500).toISOString(),
        taskId: taskId("task-103"),
        taskName: "Query Execution Profiling",
        worker: workerId("worker-node-gamma"),
        message: "Worker node gamma began executing query benchmarking suite",
      },
    ],
    "run-002": [
      {
        id: eventId("ev-201"),
        runId: runId("run-002"),
        type: "run_created",
        severity: "info",
        timestamp: new Date(baseTime - 1000 * 60 * 120).toISOString(),
        message: "Run created with goal: 'Implement comprehensive zero-trust authentication protocol'",
      },
      {
        id: eventId("ev-202"),
        runId: runId("run-002"),
        type: "run_completed",
        severity: "success",
        timestamp: new Date(baseTime - 1000 * 60 * 95).toISOString(),
        message: "All tasks completed. Run certified with 100% test coverage.",
      },
    ],
    "run-003": [
      {
        id: eventId("ev-301"),
        runId: runId("run-003"),
        type: "run_created",
        severity: "info",
        timestamp: new Date(baseTime - 1000 * 60 * 240).toISOString(),
        message: "Run created with goal: 'Automate cross-region PostgreSQL replica failover'",
      },
      {
        id: eventId("ev-302"),
        runId: runId("run-003"),
        type: "task_failed",
        severity: "error",
        timestamp: new Date(baseTime - 1000 * 60 * 210).toISOString(),
        taskId: taskId("task-302"),
        taskName: "Consensus Leader Election",
        worker: workerId("worker-node-beta"),
        message: "Task failed after 3 retry attempts: split-brain threshold reached",
      },
      {
        id: eventId("ev-303"),
        runId: runId("run-003"),
        type: "run_failed",
        severity: "error",
        timestamp: new Date(baseTime - 1000 * 60 * 210).toISOString(),
        message: "Execution run terminated with failure status.",
      },
    ],
    "run-004": [
      {
        id: eventId("ev-401"),
        runId: runId("run-004"),
        type: "run_created",
        severity: "info",
        timestamp: new Date(baseTime - 1000 * 60 * 5).toISOString(),
        message: "Run created with goal: 'Generate Diataxis-compliant architectural documentation'",
      },
    ],
  };
}
